apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: ziasaeeditgeek/three-tier-react-frontend
        ports:
        - containerPort: 3000
