apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend-deployment
  labels:
    app: django-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django-backend
        image: ziasaeeditgeek/three-tier-django-backend
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: mydb
        - name: DB_USER
          value: myuser
        - name: DB_PASSWORD
          value: mypassword
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
